### PR TITLE
Created Ternary_Search.cpp

### PR DESCRIPTION
**Pull request by YashikaGupta03**
Code for Searching using Ternary Search in which for searching array is divided into three parts.

### CODE REVIEW

**Comment by KaiAlan** [comment]
ternary search us already present

**Review by KaiAlan — APPROVED** [review]
i will merge this one as the previously present ternary search is in c language and this one in cpp

**Comment by YashikaGupta03** [comment]
ok

**Comment by YashikaGupta03** [comment]
Thank you

**Pull request merged**
